### ISSUE TITLE
当markdown比较大的时.就stackoverflow了

### ISSUE THREAD

**Issue by HumorSmith** [zzhoujay/Markdown#1]

**Comment by zzhoujay** [comment]
恩，现在很多地方都是用的递归的方式来做的，后面会慢慢优化的，感谢提出

**Comment by zzhoujay** [comment]
对了，能不能把出错的部分log贴一下，有助于我后面的优化

**Comment by HumorSmith** [comment]
错误的log。那天忘记抓了。你可以尝试一下大的markdown.应该能复现

**Comment by zzhoujay** [comment]
那能不能把引发出错的markdown文本贴一下，因为有可能是特定某些标签过多导致的问题
