### ISSUE TITLE
添加gradle支持

### ISSUE THREAD

**Issue by HumorSmith** [zzhoujay/Markdown#2]

**Comment by zzhoujay** [comment]
原本计划是把项目完善后整合进[RichText](https://github.com/zzhoujay/RichText)一起发布的，那这样吧，我周末把一些问题修复后先把这个项目单独发布一下吧

**Comment by HumorSmith** [comment]
可以.可以先分着，后面在进行合并也行

**Comment by zzhoujay** [comment]
已经上传到jcenter了，后面如果遇到一些问题的话欢迎随时反馈
`compile 'com.zzhoujay.markdown:markdown:0.0.2'`

**Comment by zzhoujay** [comment]
现在已整合进了RichText
